Mrc 2379
mrc-ide/comet pull request #12
Opened 2021-05-10 18:35 UTC by EmmaLRussell

2021-05-13 10:27 UTC, mwoodbri requested changes
Appreciate this has involved a lot of faff with Vue etc. But disregarding that I'm impressed how small this diff is, and the end result looks great!

I'm agnostic about where we rehydrate the jsonata, and shouldn't be too hard to change if we need to. On a related note... I can already see some pain from jsonata not being json, and therefore the lack of help that editor etc can provide. No easy solution for that though.

Only a couple of cosmetic issues that we might consider addressing, now or later. The accordion starts open and then immediately collapses for me - is this intended? And the spacing in form is less than ideal - if it was more full-width then the labels would be easier to read:

![comet_sidebar](https://user-images.githubusercontent.com/1724545/118113342-1288d100-b3de-11eb-86fa-ec058da35923.png)

2021-05-13 10:27 UTC, mwoodbri commented on src/app/static/src/views/Home.vue
> +        console.log("mounted");
No harm in this... but deliberate?

2021-05-13 10:53 UTC, EmmaLRussell commented
> Only a couple of cosmetic issues that we might consider addressing, now or later. The accordion starts open and then immediately collapses for me - is this intended? And the spacing in form is less than ideal - if it was more full-width then the labels would be easier to read:
> 

The collapsed sections starting off opened seems to be a limitation of the form - it happens on the example form too, so I'll see if I can fix it there. I'll see what I can do about the label wrapping here - the form does apply col classes to labels and values, but its other clients expect this.

2021-05-13 14:51 UTC, mwoodbri approved these changes
Sidebar looking great now

2021-05-14 13:45 UTC, merged

2021-05-14 13:48 UTC, carbowizzy approved these changes