Mrc 2409
mrc-ide/comet pull request #15
Opened 2021-05-18 16:09 UTC by EmmaLRussell

2021-05-19 14:35 UTC, mwoodbri reviewed
Very nice. Just two things:
* A trivial typo in test (see comment)
* Feel free to ignore this one, because it's a bit contrived. But to test errors on About page I changed URL to `/api-blah`. This is a 404 (i.e. very unlikely in real app) but `response.data` is: `{ timestamp: "2021-05-19T14:23:44.668+00:00", status: 404, error: "Not Found", message: "No message available", path: "/api-blah" }`. JSON has `error` and `message` but error handling fails because it's looking for `errors` field. Just wanted to check whether this was the scenario you were intending to deal with via `e.message` case?

2021-05-19 14:35 UTC, mwoodbri commented on src/app/static/tests/unit/components/errors.test.ts
> +    it("renders as expected with one errors", () => {
```suggestion
    it("renders as expected with one error", () => {
```

2021-05-20 09:36 UTC, Nicolas-Dolan requested changes
Works very well but it exposes a bug. When I selected HCW, Elderly and High Risk Groups, I got the error message as expected, but if I then proceeded to the About page and closed the error message there and then returned to the Home page, the error message would still be there (presumably because the error-causing selections are still in state when it is rerendered) but the actual value selected in the form would be the default HCW and Elderly. Clicking ok with the default selected would then cause nothing to happen because as far as the form is concerned I haven't changed anything. I suspect this isn't so much an issue with the error handling itself but how the state of the form and the state of the model desync when you leave the page.

Actually, on further testing, it doesn't seem to matter if you close the error message on the About page.

2021-06-01 08:57 UTC, EmmaLRussell commented
>     * Feel free to ignore this one, because it's a bit contrived. But to test errors on About page I changed URL to `/api-blah`. This is a 404 (i.e. very unlikely in real app) but `response.data` is: `{ timestamp: "2021-05-19T14:23:44.668+00:00", status: 404, error: "Not Found", message: "No message available", path: "/api-blah" }`. JSON has `error` and `message` but error handling fails because it's looking for `errors` field. Just wanted to check whether this was the scenario you were intending to deal with via `e.message` case?

Oh interesting, I didn't realise there was a case which would produce `error` rather than `errors`, will correct.

2021-06-01 09:00 UTC, EmmaLRussell commented
> Works very well but it exposes a bug. When I selected HCW, Elderly and High Risk Groups, I got the error message as expected, but if I then proceeded to the About page and closed the error message there and then returned to the Home page, the error message would still be there (presumably because the error-causing selections are still in state when it is rerendered) but the actual value selected in the form would be the default HCW and Elderly. Clicking ok with the default selected would then cause nothing to happen because as far as the form is concerned I haven't changed anything. I suspect this isn't so much an issue with the error handling itself but how the state of the form and the state of the model desync when you leave the page.
> 
> Actually, on further testing, it doesn't seem to matter if you close the error message on the About page.

Going back to the Home page will definitely generate a new error because it (currently) re-fetching results when Home is loaded, and that's what's getting the error - and it won't matter whether the first error was cleared or not. 

But you're right about the parameter not being set in the form, that should be happening even if result in an error, will investigate.

2021-06-01 10:58 UTC, EmmaLRussell commented
So the problem with losing changed parameter values on returning to Home from About is because the load of Home was always triggering a fetch of metadata, causing overwrite of parameter values with defaults. I've addressed this by not fetching on load if metadata is already set, and I've done the same thing for results too - these will be refreshed when parameter values change.

2021-06-01 14:37 UTC, mwoodbri commented on src/app/static/src/store/actions.ts
> +    if (e.response && e.response.data && e.response.data.errors) {
```suggestion
    if (e.response?.data.errors) {
```
...if you wanted to make this slightly easier to read/write

2021-06-01 14:38 UTC, mwoodbri approved these changes
Very merge-able, IMHO

2021-06-02 09:06 UTC, Nicolas-Dolan approved these changes

2021-06-02 10:29 UTC, merged