Mrc 2313
mrc-ide/comet pull request #2
Opened 2021-04-19 15:50 UTC by EmmaLRussell

2021-04-22 15:52 UTC, EmmaLRussell commented on src/app/static/.eslintrc.js
> +        "arrow-body-style": "off",
These two rules don't seem to work well with Typescript - `arrow-body-style` seems to interpret a return type as a funtion body without braces. `prefer-default-export`. And I don't think you can specify a type with default export, hence removing `prefer-default-export`.

2021-04-22 16:10 UTC, EmmaLRussell commented
@mwoodbri I just saw your comment on the ticket about replacing config.json with jsonata - makes sense, happy to do that in this branch or another.

2021-04-26 13:48 UTC, mwoodbri requested changes
I think if we're going to make `config` a string then this is the place to do it. But PR can be merged almost immediately thereafter - looks great and seems like we should nearly be able to render the actual charts with mock data as in the prototype.

Just one comment inline. Have added mrc-2358 for other unrelated things I spotted.

2021-04-26 13:48 UTC, mwoodbri commented on src/app/build.gradle.kts
> +    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
I think you can pin this to `2.12.3` and remove L26.

2021-04-27 12:11 UTC, mwoodbri requested changes
All looks great... except minor issue not addressed since original review

2021-04-27 14:12 UTC, EmmaLRussell commented
> All looks great... except minor issue not addressed since original review

:facepalm: Sorry!

2021-04-27 14:14 UTC, mwoodbri approved these changes

2021-04-27 14:26 UTC, merged